/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OnboardingClassRouteImport } from './routes/onboarding/class'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding/language'
import { Route as OnboardingPreferencesRouteImport } from './routes/onboarding/preferences'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding/review'
import { Route as OnboardingSubjectsRouteImport } from './routes/onboarding/subjects'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as AppLessonsLessonIdRouteImport } from './routes/app.lessons.$lessonId'
import { Route as AppLiveCreateRouteImport } from './routes/app.live.create'
import { Route as AppLiveJoinRouteImport } from './routes/app.live.join'
import { Route as AppSubjectsIndexRouteImport } from './routes/app.subjects.index'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/app.subjects.$subjectId'
import { Route as AppLiveTeachCodeRouteImport } from './routes/app.live.teach.$code'
import { Route as AppLiveWatchCodeRouteImport } from './routes/app.live.watch.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/app/progress',
  path: '/app/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/app/tutor',
  path: '/app/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClassRoute = OnboardingClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPreferencesRoute = OnboardingPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSubjectsRoute = OnboardingSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/app/lessons/$lessonId',
  path: '/app/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiveCreateRoute = AppLiveCreateRouteImport.update({
  id: '/app/live/create',
  path: '/app/live/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiveJoinRoute = AppLiveJoinRouteImport.update({
  id: '/app/live/join',
  path: '/app/live/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/app/subjects/',
  path: '/app/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/app/subjects/$subjectId',
  path: '/app/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiveTeachCodeRoute = AppLiveTeachCodeRouteImport.update({
  id: '/app/live/teach/$code',
  path: '/app/live/teach/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLiveWatchCodeRoute = AppLiveWatchCodeRouteImport.update({
  id: '/app/live/watch/$code',
  path: '/app/live/watch/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/class': typeof OnboardingClassRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/live/create': typeof AppLiveCreateRoute
  '/app/live/join': typeof AppLiveJoinRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
  '/app/live/teach/$code': typeof AppLiveTeachCodeRoute
  '/app/live/watch/$code': typeof AppLiveWatchCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/class': typeof OnboardingClassRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/live/create': typeof AppLiveCreateRoute
  '/app/live/join': typeof AppLiveJoinRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects': typeof AppSubjectsIndexRoute
  '/app/live/teach/$code': typeof AppLiveTeachCodeRoute
  '/app/live/watch/$code': typeof AppLiveWatchCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/class': typeof OnboardingClassRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/subjects': typeof OnboardingSubjectsRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/live/create': typeof AppLiveCreateRoute
  '/app/live/join': typeof AppLiveJoinRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
  '/app/live/teach/$code': typeof AppLiveTeachCodeRoute
  '/app/live/watch/$code': typeof AppLiveWatchCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/auth/callback'
    | '/onboarding/class'
    | '/onboarding/complete'
    | '/onboarding/language'
    | '/onboarding/preferences'
    | '/onboarding/review'
    | '/onboarding/subjects'
    | '/onboarding/welcome'
    | '/app/lessons/$lessonId'
    | '/app/live/create'
    | '/app/live/join'
    | '/app/subjects/$subjectId'
    | '/app/subjects/'
    | '/app/live/teach/$code'
    | '/app/live/watch/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/auth/callback'
    | '/onboarding/class'
    | '/onboarding/complete'
    | '/onboarding/language'
    | '/onboarding/preferences'
    | '/onboarding/review'
    | '/onboarding/subjects'
    | '/onboarding/welcome'
    | '/app/lessons/$lessonId'
    | '/app/live/create'
    | '/app/live/join'
    | '/app/subjects/$subjectId'
    | '/app/subjects'
    | '/app/live/teach/$code'
    | '/app/live/watch/$code'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/auth/callback'
    | '/onboarding/class'
    | '/onboarding/complete'
    | '/onboarding/language'
    | '/onboarding/preferences'
    | '/onboarding/review'
    | '/onboarding/subjects'
    | '/onboarding/welcome'
    | '/app/lessons/$lessonId'
    | '/app/live/create'
    | '/app/live/join'
    | '/app/subjects/$subjectId'
    | '/app/subjects/'
    | '/app/live/teach/$code'
    | '/app/live/watch/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppTutorRoute: typeof AppTutorRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppLiveCreateRoute: typeof AppLiveCreateRoute
  AppLiveJoinRoute: typeof AppLiveJoinRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
  AppLiveTeachCodeRoute: typeof AppLiveTeachCodeRoute
  AppLiveWatchCodeRoute: typeof AppLiveWatchCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/app/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/app/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/class': {
      id: '/onboarding/class'
      path: '/class'
      fullPath: '/onboarding/class'
      preLoaderRoute: typeof OnboardingClassRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/preferences': {
      id: '/onboarding/preferences'
      path: '/preferences'
      fullPath: '/onboarding/preferences'
      preLoaderRoute: typeof OnboardingPreferencesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/subjects': {
      id: '/onboarding/subjects'
      path: '/subjects'
      fullPath: '/onboarding/subjects'
      preLoaderRoute: typeof OnboardingSubjectsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/lessons/$lessonId': {
      id: '/app/lessons/$lessonId'
      path: '/app/lessons/$lessonId'
      fullPath: '/app/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/live/create': {
      id: '/app/live/create'
      path: '/app/live/create'
      fullPath: '/app/live/create'
      preLoaderRoute: typeof AppLiveCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/live/join': {
      id: '/app/live/join'
      path: '/app/live/join'
      fullPath: '/app/live/join'
      preLoaderRoute: typeof AppLiveJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subjects/': {
      id: '/app/subjects/'
      path: '/app/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subjects/$subjectId': {
      id: '/app/subjects/$subjectId'
      path: '/app/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/live/teach/$code': {
      id: '/app/live/teach/$code'
      path: '/app/live/teach/$code'
      fullPath: '/app/live/teach/$code'
      preLoaderRoute: typeof AppLiveTeachCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/live/watch/$code': {
      id: '/app/live/watch/$code'
      path: '/app/live/watch/$code'
      fullPath: '/app/live/watch/$code'
      preLoaderRoute: typeof AppLiveWatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingClassRoute: typeof OnboardingClassRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingPreferencesRoute: typeof OnboardingPreferencesRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingSubjectsRoute: typeof OnboardingSubjectsRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingClassRoute: OnboardingClassRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingPreferencesRoute: OnboardingPreferencesRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingSubjectsRoute: OnboardingSubjectsRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppTutorRoute: AppTutorRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppLiveCreateRoute: AppLiveCreateRoute,
  AppLiveJoinRoute: AppLiveJoinRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
  AppLiveTeachCodeRoute: AppLiveTeachCodeRoute,
  AppLiveWatchCodeRoute: AppLiveWatchCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
